channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=25.2
- pip:
  - mlflow==3.9.0
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.3.1
  - psutil==7.2.1
  - pyarrow==21.0.0
  - scikit-learn==1.7.1
  - scipy==1.15.3
  - xgboost==1.7.6
name: mlflow-env
